version: '3'

services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./conf/myrabbit.conf:/etc/rabbitmq/rabbitmq.config
    networks:
      - messaging

networks:
  messaging:
    driver: bridge
